# Generated by Django 2.1.1 on 2019-02-06 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='articles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=300)),
                ('Topic', models.CharField(max_length=500)),
                ('Content', models.CharField(max_length=2000)),
            ],
        ),
    ]
