# Generated by Django 2.1.1 on 2019-02-12 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lean', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='posts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=300)),
                ('Topic', models.CharField(max_length=500)),
                ('Content', models.CharField(max_length=5000)),
            ],
        ),
        migrations.AlterField(
            model_name='articles',
            name='Content',
            field=models.CharField(max_length=5000),
        ),
    ]
