# Generated by Django 2.1.1 on 2019-02-16 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lean', '0002_auto_20190212_1645'),
    ]

    operations = [
        migrations.CreateModel(
            name='bangalore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=300)),
                ('Comment', models.CharField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='chennai',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=300)),
                ('Comment', models.CharField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='delhi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=300)),
                ('Comment', models.CharField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='mumbai',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=300)),
                ('Comment', models.CharField(max_length=2000)),
            ],
        ),
    ]
